/*
 * This source file was generated by the Gradle 'init' task
 */
package putter;

import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.requests.GatewayIntent;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        String BOT_TOKEN = System.getenv("BOT_TOKEN");

        JDABuilder.createDefault(BOT_TOKEN) // enable all default intents
                .enableIntents(GatewayIntent.GUILD_MEMBERS) // also enable privileged intent
                .enableIntents(GatewayIntent.MESSAGE_CONTENT)
                .addEventListeners(new MyListener())
                .build();

    }
}
